name: clique
description: "Your vibe, your clique"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^8.1.0
  shimmer: ^3.0.0

  # State Management
  flutter_bloc: ^9.1.1
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # Image & Media
  flutter_blurhash: ^0.9.1
  image_picker: ^1.0.7
  mime: ^2.0.0
  fl_chart: ^1.2.0

  # Chat
  flutter_chat_ui: ^2.11.1
  flutter_chat_types: ^3.6.2
  uuid: ^4.2.1

  # Network & API
  dio: ^5.9.2
  retrofit: ^4.0.1
  logger: ^2.7.0
  pretty_dio_logger: ^1.3.0

  # Auth & Backend
  supabase_flutter: ^2.12.4
  flutter_secure_storage: ^10.0.0
  local_auth: ^3.0.1
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4

  # Cloud Storage
  cloudinary_public: ^0.23.0
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0

  # Video & Media
  video_player: ^2.11.1
  cached_network_image: ^3.4.1
  http_parser: ^4.1.2
  path_provider: ^2.1.5
  path: ^1.9.1
  http: ^1.6.0

  # Storage
  shared_preferences: ^2.5.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Animations
  animate_do: ^5.1.0
  lottie: ^3.3.3
  animations: ^2.0.7
  simple_animations: ^5.0.2
  equatable: ^2.0.8
  bloc: ^9.2.0
  open_file: ^3.5.11
  file_picker: ^12.0.0-beta.4
  url_launcher: ^6.3.2
  audio_waveforms: ^2.0.2
  just_audio: ^0.10.5
  cloudinary: ^1.2.0
  purchases_flutter: ^10.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^4.0.3
  retrofit_generator: ^10.2.6
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  app_links: 7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/profiles/
    - assets/animations/
    - assets/icons/
    - assets/wallpapers/
    - assets/sounds/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/clique.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_padding: false
  adaptive_icon_foreground: "assets/icons/clique.png"
